"""empty message

Revision ID: 28ebe6cb8bef
Revises: 59afa21b8e56
Create Date: 2014-07-22 18:20:53.203000

"""

# revision identifiers, used by Alembic.
revision = '28ebe6cb8bef'
down_revision = '59afa21b8e56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
