"""empty message

Revision ID: 34e8fb3c02b7
Revises: None
Create Date: 2014-07-16 18:10:36.328000

"""

# revision identifiers, used by Alembic.
revision = '34e8fb3c02b7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
